export const SAVE_EXPERIENCE = "SAVE_EXPERIENCE";

export const SAVE_EDUCATION = "SAVE_EDUCATION";

export const SAVE_STUD_OBJECT = "SAVE_STUD_OBJECT";

export const FETCH_PROFILE = "FETCH_PROFILE";

export const DELETE_EDUCATION = "DELETE_EDUCATION";

export const DELETE_EXPERIENCE = "DELETE_EXPERIENCE";