export const FETCH_STUDENTDETAILS = "FETCH_STUDENTDETAILS";
export const FETCH_EDUCATION = "FETCH_EDUCATION";
export const FETCH_WORKEXP = "FETCH_WORKEXP";
export const FETCH_STUDENT = "FETCH_STUDENT";

export const EDIT_MYJOURNEY = "EDIT_MYJOURNEY";
export const EDIT_MYSKILLS = "EDIT_MYSKILLS";
export const EDIT_CONTACTDETAILS = "EDIT_CONTACTDETAILS";
export const EDIT_MYEDU = "EDIT_MYEDU";
export const EDIT_MYWORK = "EDIT_MYWORK";
export const REMOVE_MYEDU = "REMOVE_MYEDU";
export const REMOVE_MYWORK = "REMOVE_MYWORK";
export const EDIT_PERSONALINFO = "EDIT_PERSONALINFO";
export const ADD_EDU = "ADD_EDU";
export const ADD_WORK = "ADD_WORK";

export const LOGIN = "LOGIN";
export const STUDENT_REGISTER = "STUDENT_REGISTER";
export const FETCH_COMPANY_PROFILE = "FETCH_COMPANY_PROFILE";
